"""add comparison mode to problems

Revision ID: 9dff68852915
Revises: bcd4107fc7c3
Create Date: 2026-07-30 15:23:04.953860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dff68852915'
down_revision: Union[str, Sequence[str], None] = 'bcd4107fc7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('comparison', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'comparison')
    # ### end Alembic commands ###
